site_name: MusicalNinjas

nav:
  - Welcome: 'index.md'
  - Libraries: '*include ./lib/*/mkdocs.yml'

theme:
  name: "material"
  features:
  - navigation.expand
  - navigation.path
  - navigation.indexes

plugins:
  - monorepo